#!/usr/bin/env bash

printf "Installing sewing-kit...\n"

# Update PATH to include sewing-ket
update_path() {
  printf "\nPlease provide the full path to your .bashrc or .zshrc file:\n"
  read rcpath

  # Make sure file exists
  if [ ! -f $rcpath ]; then
    printf "\nERROR: Cannot find file at $rcpath\n"
    exit 1
  fi

  printf '\n%s\n%s\n%s\n' '# Auto generated by sewing-kit' "export PATH=\$PATH:$PWD/bin" '$(upgrade-swk check)' >> $rcpath
  if cat $rcpath | grep -q '# Auto generated by sewing-kit'; then
    printf "\nPath added successfully\n"
  else
    printf "\nFailed to updated $rcpath, please add export PATH=\$PATH:$PWD/bin to the proper .*rc file\n"
  fi
}

# Check if sewing-kit has been downloaded
if [ ! -f install.sh ]; then
  git clone https://github.com/StepsAway/sewing-kit.git
fi

# Copy over development.conf template
if [ -f ~/.development.conf ]; then
  printf "\n$HOME/.development.conf already exists, would you like to overwrite it?\n"
  select yn in "Yes" "No"; do
    case $yn in
      Yes ) cp config/development.conf ~/.development.conf; break;;
      No ) break;;
    esac
  done
else
  cp config/development.conf ~/.development.conf
fi

# Add to bin to PATH
printf "\nDo you wish sewing-kit to be added to your PATH (Recommended)\n"
select yn in "Yes" "No"; do
  case $yn in
    Yes ) update_path; break;;
    No ) break;;
  esac
done

printf "Finished with sewing-kit install!\nYou can manually update it anytime by running: upgrade-swk\n"
